function oz2_compile

disp('now: compiling oz2.cu ...')
try

    mexcuda oz2.cu ...
        -R2018a ...
        -lcuda -lcudart -lcublas ...
        -Llib -lgemmul8 -Iinclude. ...
        -silent ...
        CXXFLAGS='$CXXFLAGS -O3 -std=c++17' ...
        COMPFLAGS='$COMPFLAGS -O3 -std=c++17' ...
        NVCCFLAGS='--allow-unsupported-compiler -D_ALLOW_COMPILER_AND_STL_VERSION_MISMATCH -O3 -std=c++17'

catch

    error(...
        "error." + newline + ...
        "try this command: " + newline + ...
        "setenv(""NVCC_APPEND_FLAGS"", '-allow-unsupported-compiler');");

end

disp('done!');

end